import { User, Post, Story, Notification, Comment } from "@/types";

export const MOCK_USERS: User[] = [
  {
    id: "1",
    username: "youruselfhere",
    displayName: "Your Name",
    avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=me&backgroundColor=b6e3f4",
    bio: "Living the pixel life ✨ | Designer & Creator",
    website: "pixora.app",
    followers: 1284,
    following: 342,
    postsCount: 47,
    isVerified: true,
    isFollowing: false,
    hasStory: true,
    storyViewed: false,
    isPrivate: false,
    location: "Jakarta, ID",
    joinedAt: "2022-01-15",
  },
  {
    id: "2",
    username: "ariadesign",
    displayName: "Aria Santoso",
    avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=aria&backgroundColor=ffd5dc",
    bio: "UI/UX Designer ✦ Making beautiful things",
    website: "aria.design",
    followers: 24800,
    following: 890,
    postsCount: 312,
    isVerified: true,
    isFollowing: true,
    hasStory: true,
    storyViewed: false,
    isPrivate: false,
    location: "Bali, ID",
    joinedAt: "2021-03-20",
  },
  {
    id: "3",
    username: "rafiphotos",
    displayName: "Rafi Kurniawan",
    avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=rafi&backgroundColor=c0aede",
    bio: "📷 Photographer | Nature & Street",
    followers: 8920,
    following: 412,
    postsCount: 189,
    isVerified: false,
    isFollowing: true,
    hasStory: true,
    storyViewed: true,
    isPrivate: false,
    location: "Yogyakarta, ID",
    joinedAt: "2021-07-12",
  },
  {
    id: "4",
    username: "zara.travels",
    displayName: "Zara Putri",
    avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=zara&backgroundColor=d1f4d1",
    bio: "🌍 Travel & Lifestyle | 40 countries",
    website: "zaratravels.com",
    followers: 54200,
    following: 1240,
    postsCount: 567,
    isVerified: true,
    isFollowing: false,
    hasStory: true,
    storyViewed: false,
    isPrivate: false,
    location: "Worldwide",
    joinedAt: "2020-05-08",
  },
  {
    id: "5",
    username: "kevin.tech",
    displayName: "Kevin Wijaya",
    avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=kevin&backgroundColor=ffe4c4",
    bio: "💻 Full-Stack Dev | Building cool stuff",
    followers: 3450,
    following: 678,
    postsCount: 92,
    isVerified: false,
    isFollowing: true,
    hasStory: false,
    storyViewed: false,
    isPrivate: false,
    location: "Surabaya, ID",
    joinedAt: "2022-11-30",
  },
  {
    id: "6",
    username: "lina.art",
    displayName: "Lina Hartono",
    avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=lina&backgroundColor=ffeaaf",
    bio: "🎨 Digital Artist | Commissions open",
    followers: 12300,
    following: 2100,
    postsCount: 234,
    isVerified: false,
    isFollowing: false,
    hasStory: true,
    storyViewed: false,
    isPrivate: false,
    location: "Bandung, ID",
    joinedAt: "2021-09-14",
  },
  {
    id: "7",
    username: "chef.budi",
    displayName: "Budi Santana",
    avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=budi&backgroundColor=b6e3f4",
    bio: "👨‍🍳 Chef | Indonesian Cuisine",
    followers: 7820,
    following: 340,
    postsCount: 156,
    isVerified: false,
    isFollowing: true,
    hasStory: true,
    storyViewed: false,
    isPrivate: false,
    location: "Jakarta, ID",
    joinedAt: "2022-02-28",
  },
  {
    id: "8",
    username: "maya.fitness",
    displayName: "Maya Indah",
    avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=maya&backgroundColor=d1f4d1",
    bio: "💪 Fitness Coach | @mayafitness",
    followers: 31000,
    following: 560,
    postsCount: 403,
    isVerified: true,
    isFollowing: false,
    hasStory: true,
    storyViewed: true,
    isPrivate: false,
    location: "Jakarta, ID",
    joinedAt: "2020-08-15",
  },
];

export const MOCK_POSTS: Post[] = [
  {
    id: "p1",
    author: MOCK_USERS[1],
    images: [
      "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&q=80",
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    ],
    caption: "New UI project I've been working on 🎨 Clean, minimal, and purposeful design. What do you think? Drop your feedback below! #uidesign #minimalism #productdesign",
    likes: 1284,
    comments: 47,
    saves: 234,
    shares: 89,
    isLiked: false,
    isSaved: false,
    tags: ["uidesign", "minimalism", "productdesign"],
    location: "Bali, Indonesia",
    createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
  {
    id: "p2",
    author: MOCK_USERS[2],
    images: [
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    ],
    caption: "Golden hour at Bromo 🌋 Nature never fails to amaze me. This shot was taken during the most perfect sunrise of my life. #landscape #bromo #indonesia #photography",
    likes: 3421,
    comments: 112,
    saves: 890,
    shares: 234,
    isLiked: true,
    isSaved: true,
    tags: ["landscape", "bromo", "indonesia", "photography"],
    location: "Mt. Bromo, East Java",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
  },
  {
    id: "p3",
    author: MOCK_USERS[3],
    images: [
      "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&q=80",
      "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=800&q=80",
      "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80",
    ],
    caption: "Switzerland was a dream 🇨🇭✨ Three days, three different vibes. The mountains, the lakes, the serenity. Adding this to my top 5 forever. #switzerland #travel #mountains #wanderlust",
    likes: 8920,
    comments: 342,
    saves: 1240,
    shares: 567,
    isLiked: false,
    isSaved: false,
    tags: ["switzerland", "travel", "mountains", "wanderlust"],
    location: "Interlaken, Switzerland",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
  },
  {
    id: "p4",
    author: MOCK_USERS[5],
    images: [
      "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=800&q=80",
    ],
    caption: "Commission done! Digital portrait study in watercolor style 🖌️ So happy with how the colors blended. DM for commissions! #digitalart #illustration #portrait #art",
    likes: 2103,
    comments: 89,
    saves: 456,
    shares: 112,
    isLiked: true,
    isSaved: false,
    tags: ["digitalart", "illustration", "portrait", "art"],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
  },
  {
    id: "p5",
    author: MOCK_USERS[6],
    images: [
      "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80",
      "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800&q=80",
    ],
    caption: "Rendang weekend 🍖❤️ Slow-cooked for 4 hours and worth every second. Full recipe on my website! #food #indonesianfood #rendang #cooking #homecook",
    likes: 5678,
    comments: 234,
    saves: 1890,
    shares: 890,
    isLiked: false,
    isSaved: true,
    tags: ["food", "indonesianfood", "rendang", "cooking"],
    location: "Jakarta, Indonesia",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
  {
    id: "p6",
    author: MOCK_USERS[7],
    images: [
      "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&q=80",
    ],
    caption: "Morning workout done ✅💪 30 min HIIT + 20 min stretching. Remember: consistency > perfection. Tag someone who needs to see this! #fitness #workout #motivation #health",
    likes: 12400,
    comments: 567,
    saves: 2340,
    shares: 1230,
    isLiked: false,
    isSaved: false,
    tags: ["fitness", "workout", "motivation", "health"],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(),
  },
  {
    id: "p7",
    author: MOCK_USERS[4],
    images: [
      "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&q=80",
    ],
    caption: "Just shipped my side project after 3 months of nights and weekends 🚀 Built with Next.js, Tailwind, and a lot of coffee. Link in bio! #webdev #nextjs #coding #buildinpublic",
    likes: 892,
    comments: 78,
    saves: 234,
    shares: 145,
    isLiked: true,
    isSaved: true,
    tags: ["webdev", "nextjs", "coding", "buildinpublic"],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
  },
];

export const MOCK_EXPLORE_POSTS: Post[] = [
  ...MOCK_POSTS,
  {
    id: "e1",
    author: MOCK_USERS[1],
    images: ["https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80"],
    caption: "Time is precious ⌚",
    likes: 4523,
    comments: 67,
    saves: 890,
    shares: 234,
    isLiked: false,
    isSaved: false,
    tags: ["watch", "luxury", "style"],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
  },
  {
    id: "e2",
    author: MOCK_USERS[3],
    images: ["https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80"],
    caption: "Paradise found 🏖️",
    likes: 8901,
    comments: 234,
    saves: 1230,
    shares: 456,
    isLiked: true,
    isSaved: false,
    tags: ["beach", "travel", "summer"],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 96).toISOString(),
  },
  {
    id: "e3",
    author: MOCK_USERS[5],
    images: ["https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=800&q=80"],
    caption: "Artwork series vol.3 🎨",
    likes: 3421,
    comments: 145,
    saves: 678,
    shares: 123,
    isLiked: false,
    isSaved: false,
    tags: ["art", "abstract", "painting"],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 100).toISOString(),
  },
  {
    id: "e4",
    author: MOCK_USERS[7],
    images: ["https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&q=80"],
    caption: "Gym life 💪",
    likes: 6789,
    comments: 289,
    saves: 1456,
    shares: 678,
    isLiked: false,
    isSaved: false,
    tags: ["gym", "fitness", "lifestyle"],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 120).toISOString(),
  },
  {
    id: "e5",
    author: MOCK_USERS[6],
    images: ["https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?w=800&q=80"],
    caption: "Breakfast goals ☀️",
    likes: 2890,
    comments: 123,
    saves: 567,
    shares: 234,
    isLiked: true,
    isSaved: true,
    tags: ["food", "breakfast", "healthy"],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 144).toISOString(),
  },
  {
    id: "e6",
    author: MOCK_USERS[2],
    images: ["https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80"],
    caption: "Architecture is poetry 🏛️",
    likes: 5432,
    comments: 189,
    saves: 890,
    shares: 345,
    isLiked: false,
    isSaved: false,
    tags: ["architecture", "urban", "minimal"],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 168).toISOString(),
  },
];

export const MOCK_STORIES: Story[] = MOCK_USERS.filter(u => u.hasStory).map((user, i) => ({
  id: `s${i}`,
  author: user,
  media: MOCK_POSTS[i % MOCK_POSTS.length]?.images[0] || "",
  type: "image" as const,
  duration: 5,
  views: Math.floor(Math.random() * 5000) + 100,
  createdAt: new Date(Date.now() - 1000 * 60 * 60 * (i + 1)).toISOString(),
  expiresAt: new Date(Date.now() + 1000 * 60 * 60 * (24 - i)).toISOString(),
}));

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: "n1",
    type: "like",
    actor: MOCK_USERS[1],
    post: MOCK_POSTS[0],
    message: "liked your photo",
    isRead: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
  },
  {
    id: "n2",
    type: "follow",
    actor: MOCK_USERS[3],
    message: "started following you",
    isRead: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: "n3",
    type: "comment",
    actor: MOCK_USERS[4],
    post: MOCK_POSTS[1],
    message: "commented: \"Stunning shot! 🔥\"",
    isRead: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
  },
  {
    id: "n4",
    type: "like",
    actor: MOCK_USERS[5],
    post: MOCK_POSTS[2],
    message: "liked your photo",
    isRead: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
  },
  {
    id: "n5",
    type: "mention",
    actor: MOCK_USERS[2],
    post: MOCK_POSTS[3],
    message: "mentioned you in a post",
    isRead: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
  },
  {
    id: "n6",
    type: "follow",
    actor: MOCK_USERS[6],
    message: "started following you",
    isRead: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
  },
  {
    id: "n7",
    type: "save",
    actor: MOCK_USERS[7],
    post: MOCK_POSTS[4],
    message: "saved your post",
    isRead: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
  },
];

export const MOCK_COMMENTS: Comment[] = [
  {
    id: "c1",
    author: MOCK_USERS[4],
    text: "This is absolutely stunning! Love the color palette 🎨",
    likes: 24,
    isLiked: false,
    replies: [
      {
        id: "c1r1",
        author: MOCK_USERS[1],
        text: "Thank you so much! 🙏 Really happy with how it turned out",
        likes: 8,
        isLiked: false,
        replies: [],
        createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
      },
    ],
    createdAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
  },
  {
    id: "c2",
    author: MOCK_USERS[3],
    text: "Can't believe the detail in this work! How long did it take?",
    likes: 12,
    isLiked: true,
    replies: [],
    createdAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
  },
  {
    id: "c3",
    author: MOCK_USERS[7],
    text: "Incredible as always! Please never stop creating 💫",
    likes: 31,
    isLiked: false,
    replies: [],
    createdAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
  },
];

export function formatCount(n: number): string {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 1_000) return `${(n / 1_000).toFixed(1)}K`;
  return n.toString();
}

export function timeAgo(date: string): string {
  const seconds = Math.floor((Date.now() - new Date(date).getTime()) / 1000);
  if (seconds < 60) return `${seconds}s`;
  if (seconds < 3600) return `${Math.floor(seconds / 60)}m`;
  if (seconds < 86400) return `${Math.floor(seconds / 3600)}h`;
  if (seconds < 604800) return `${Math.floor(seconds / 86400)}d`;
  return `${Math.floor(seconds / 604800)}w`;
}
